# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4856686252b39c8a95a25aeda3fbef3d256bc5f18a32ad3f0cf7339d9c06bf617de46afbf0ec3826f8b68c7457d6dd0b654475a663fefb2e6c940e879567b61

test:
  secret_key_base: 771285ffefd20f5a30a5c47aaad50eacff7c96b4e8f8595cfd7ed34819d5265058664f7a9bff52f4f3e94d1395dad986e7fa0a640a4cfbf85dcaf894fc36d491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
